#pragma once

#define RES_PATH_MAPS_DEFAULT_BACKGROUND "../src/Game/Resources/Maps/Default/map1_background.png"
#include "Maps/LudusMap/LudusMapResources.h"
#define RES_PATH_CHARACTERS_DEFAULT "../src/Game/Resources/Characters/Character1.png"
#define RES_PATH_CHARACTERS_MAGE "../src/Game/Resources/Characters/Mage.png"
#define RES_PATH_CHARACTERS_PIRATE "../src/Game/Resources/Characters/Pirate.png"
#define RES_PATH_CHARACTERS_BULLY "../src/Game/Resources/Characters/Bully.png"
#define RES_PATH_PROJECTILES_MAGE "../src/Game/Resources/Projectiles/Fireball.png"
#define RES_PATH_PROJECTILES_PIRATE "../src/Game/Resources/Projectiles/Cannonball.png"
#define RES_PATH_PROJECTILES_MARK "../src/Game/Resources/Projectiles/Mark.png"
#define RES_PATH_PROJECTILES_BULLY "../src/Game/Resources/Projectiles/Bat.png"
#define RES_PATH_PARTICLES_EXPLOSION "../src/Game/Resources/Particles/Explosion.png"
#define RES_PATH_PARTICLES_SMOKE "../src/Game/Resources/Particles/Smoke.png"
#define RES_PATH_PARTICLES_HIT "../src/Game/Resources/Particles/Hit.png"
#define RES_PATH_PARTICLES_POWERUP "../src/Game/Resources/Particles/PowerUp.png"
#define RES_PATH_ZONES_DAMAGE "../src/Game/Resources/Zones/HazardZone.png"
#define RES_PATH_UI_AIM "../src/Game/Resources/UI/Aim.png"
#define RES_PATH_UI_WIN "../src/Game/Resources/UI/Win.png"
#define RES_PATH_UI_LOSE "../src/Game/Resources/UI/Lose.png"
#define RES_PATH_POWERUP_HEALTH "../src/Game/Resources/PowerUps/HealthPU.png"
#define RES_PATH_POWERUP_DAMAGE "../src/Game/Resources/PowerUps/DamagePU.png"
#define RES_PATH_POWERUP_SPEED "../src/Game/Resources/PowerUps/SpeedPU.png"